#ifndef PUCKCONTROLLER_GLOBAL_H
#define PUCKCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PUCKCONTROLLER_LIBRARY)
#  define PUCKCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PUCKCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PUCKCONTROLLER_GLOBAL_H
